backend/config/config.go, backend/models/base.go
https://docs.google.com/spreadsheets/d/1JORk2SgqLNulOah5uCl1c72ULWAL_gHJwRHTRO5A3NA/edit#gid=0
https://docs.google.com/document/d/186f5OePZpAkEO2uvvmK4DDEVmk32KY-c-iaUZ7v-qjg/edit
dbのテーブル名を設定した
dbを作成するSQLクエリを実行している。
=> add: channel関連のdbを作成

backend/controllers/channel.go, backend/controllers/channel_test.go, backend/controllers/setup.go, backend/controllers/user.go, backend/controllers/workspace.go, backend/models/channels.go, backend/models/channels_and_users.go, backend/models/channels_and_users_test.go, backend/models/channels_and_workspaces.go, backend/models/channels_and_workspaces_test.go, backend/models/workspace_and_users.go, backend/token/token.go
channelにユーザーを追加するcontrollerを作成！
昨日と同じように見てもらえるとありがたいです。
=> add: addUserInChannel controllers

.vscode/settings.json, backend/controllers/channel.go, backend/controllers/channel_test.go, backend/controllers/setup.go, backend/models/channels.go, backend/models/channels_and_users.go, backend/models/channels_and_users_test.go, backend/models/channels_and_workspaces.go, backend/models/channels_and_workspaces_test.go, backend/models/channels_test.go
=> add: deleteChannel controllers

backend/controllers/message.go, backend/controllers/message_test.go, backend/controllers/setup.go, backend/controllers/user.go, backend/controllers/user_test.go, backend/models/base.go
昨日作ったchannel内のmessageを取得するAPIのテストを行った
=> add: get message from channel controller test

backend/controllerUtils/check_existing_test.go, backend/controllers/workspace.go, backend/models/channels.go, backend/models/messages.go, backend/models/messages_test.go, backend/models/workspace.go, backend/models/workspace_test.go, backend/token/token_test.go
新しくDBに登録するStructのIDをそれまでのDBに存在するIDの最大値 + 1に変更した
=> 50-modelsのcreate-methodのidの決め方を変更する

backend/controllerUtils/get_from_tables.go, backend/controllers/channel.go, backend/controllers/channel_test.go, backend/controllers/setup.go, backend/models/channels.go, backend/models/channels_and_users.go, backend/models/channels_and_users_test.go, backend/models/channels_test.go, backend/models/messages_test.go
仕様書
https://www.notion.so/get-channels-by-userId-and-workspaceId-API-b4af50588af9455cbe19be5ca9b24246?pvs=4
=> 53 特定のworkspaceに存在するchannelの情報を返すapiを作成する

backend/controllerUtils/check_existing.go, backend/controllerUtils/get_from_tables.go, backend/controllers/setup.go, backend/controllers/workspace.go, backend/controllers/workspace_test.go, backend/models/messages_test.go, backend/models/user.go, backend/models/user_test.go, backend/models/workspace_and_users.go, backend/models/workspace_and_users_test.go
userの情報として、id, username, role_idを返すようにしました。
仕様書
https://www.notion.so/get-users-in-workspace-API-9629a2e8b00e48c7b58ef439ad1204aa?pvs=4
=> 54 特定のworkspaceに存在するuserの情報を返すapiを作成する

backend/models/channels.go, backend/models/channels_and_users.go, backend/models/workspace_and_users.go
=> fix: 最近のAPIで使用しているSQLの?を$xに変換

backend/controllerUtils/check_existing.go, backend/controllerUtils/input.go, backend/controllerUtils/permissions.go, backend/controllers/direct_message.go, backend/controllers/direct_message_test.go, backend/controllers/setup.go, backend/models/direct_messages.go, backend/models/direct_messages_test.go
https://www.notion.so/edit-dm-API-5283094bb1994f338274c3a64d6dfa5f?pvs=4
=> add: edit DM API

frontend/pages/component/channel_index.tsx, frontend/pages/component/workspace_index.tsx, frontend/pages/fetchAPI/channel.ts
画面遷移がまだできてないので、workspace_idは仮置きです。
urlから持ってこれるようになったら修正します。
=> チャンネル一覧の取得

backend/controllers/direct_message.go, backend/controllers/direct_message_test.go, backend/controllers/setup.go, backend/models/direct_messages.go, backend/models/direct_messages_test.go
https://www.notion.so/delete-DM-API-ef111c8bde804101b0d583609ebc1edb?pvs=4
=> add: delete dm API

backend/controllerUtils/check_existing.go, backend/controllerUtils/check_existing_test.go, backend/controllerUtils/input.go, backend/controllerUtils/permissions.go, backend/controllers/message.go, backend/controllers/message_test.go, backend/controllers/setup.go, backend/models/messages.go, backend/models/messages_test.go
=> add: edit message API

backend/controllers/workspace.go, backend/controllers/workspace_test.go
=> fix: 500番エラー

backend/models/messages.go
一応DBのカラムを変更しているので、SlackCloneApp.sqlを削除してください！
=> delete: Date column

backend/controllers/channel.go, backend/controllers/direct_message.go, backend/controllers/user.go, backend/controllers/workspace.go, backend/models/base.go
複数のデータベーステーブルを操作している箇所でエラーが発生した時に、ロールバックするようにした
=> add: トランザクションを実装

backend/controllerUtils/input.go, backend/controllers/direct_message_test.go, backend/controllers/message.go, backend/controllers/message_test.go, backend/controllers/thread_test.go, backend/controllers/threads.go, backend/models/base.go, backend/models/mention.go, backend/models/mention_test.go
メッセージにメンションの情報があった際に処理する仕組みを追加した。
=> 152 メンション機能を作成

backend/controllerUtils/check_existing.go, backend/controllerUtils/get_from_tables.go, backend/controllers/setup.go, backend/controllers/thread_test.go, backend/controllers/threads.go
**やったこと**
- TestGetThreadsByUser funcを追加
- GetThreadsByUserAPIがworkspaceごとの情報を返すように変更
- PostThread func内で、parentMessageとなったmessageを送信したUserのデータベースに保存するように変更
=> 149 get threads by user func のテスト

backend/controllerUtils/get_from_tables.go, backend/controllers/channel.go, backend/controllers/channel_test.go, backend/controllers/setup.go
すべてのpublicチャンネルと、userが所属しているprivateチャンネルを返すようにしてます
=> 171 workspaceに存在するchannelを返すapiを作成する

frontend/src/components/sideNav1/show_workspaces.tsx, frontend/src/components/sideNav2/show_channels/[id].tsx, frontend/src/fetchAPI/workspace.ts
結局「131-get-users-in-workspace-api作成-1」のpushの仕方がよく分からなかったので、新しく 作ることにしました。
遅くなってしまって申し訳ないです！！！
=> 現状把握のやり直しpushです。

backend/controllers/message.go, backend/models/base.go, backend/models/messages_and_users.go, backend/models/messages_and_users_test.go
userが特定のmessageを見たのかを記録するDBを追加。
sendMessage API内にchannel内にいる人 or DMの相手のUserをとりあえず、DBに追加するようにした
=> add: message_and_users table

frontend/package.json, frontend/src/components/sideNav1/show_workspaces.tsx, frontend/src/components/sideNav2/show_channels/[id].tsx, frontend/src/fetchAPI/workspace.ts, frontend/src/pages/route.tsx, frontend/src/pages/sideNav1.tsx
- recoilの導入、動作テスト
- 命名改善
workspaceにアクセスするタイミングでユーザー一覧を取得する
それをusersInWStateとしてatomに保存する
useRecoilValueを使ってユーザー一覧を取り出すことができた
取り出し方
`const usersInW = useRecoilValue(usersInWState)`
=> 176 fix get users in workspace

frontend/package.json, frontend/postcss.config.js, frontend/src/pages/header.tsx, frontend/src/styles/globals.css, frontend/tailwind.config.js
tailwindcssの環境構築してみました。一度このブランチをローカルにpullして、動作確認をお願いしたいです。下記画像のようにheaderの文字が赤になっていたら成功かと思います。下記画像を参照。tailwindcss自体に関して、質問があれば専用のSlackチャンネルを作成するので、そこでお願いしたいです。
チャンネルのURL: https://w1677379737-civ649113.slack.com/archives/C0578MSLHFZ
1. docker-compose down
2. docker-compose up
3. localhostにアクセス
https://zenn.dev/shimakaze_soft/articles/0ce52691b6fc3e
=> add: tailwindcss

frontend/src/components/main/signUp_form.tsx, frontend/src/components/main/user.tsx, frontend/src/components/popUp/create_channel.tsx, frontend/src/components/sideNav1/create_workspace.tsx, frontend/src/components/sideNav1/show_workspaces.tsx, frontend/src/components/sideNav2/show_channels/[id].tsx, frontend/src/pages/main/login_form.tsx, frontend/src/pages/main/signUp_form.tsx, frontend/src/pages/sideNav1.tsx, frontend/src/pages/sideNav2.tsx
formのバリデーションを設定しました（必須入力、文字数制限）
- ログイン
- 新規登録
- チャンネル作成
- ワークスペース作成
=> 169 form validation

frontend/src/utils/searchUsers.ts
動作テスト方法
user名はtest userでテスト
input = 'ts' -> NG
input = 'tu' -> OK
input = 't' -> OK
input = 'tes' -> OK
とりあえず、動作しているはずです。これから改善の余地あり。みんなで改善してければよき。
=> add: search user func

backend/controllerUtils/check_existing.go, backend/controllers/message.go
全く同じ処理をしている関数があったので片方を削除しました。テストは全部パスしました。
=> IsExistDMById関数を削除

frontend/src/components/main/send_message.tsx, frontend/src/components/main/show_messages.tsx, frontend/src/components/sideNav2/show_channels/[id].tsx, frontend/src/fetchAPI/channel.ts, frontend/src/fetchAPI/message.ts, frontend/src/pages/main.tsx, frontend/src/pages/main/channel.tsx, frontend/src/pages/route.tsx
メッセージ送信と、チャンネル内のメッセージを取得する機能を実装しました。
=> add: channel component

backend/controllers/channel.go, backend/controllers/channel_test.go, backend/controllers/setup.go, backend/controllers/test_func.go
channelに参加しているユーザーの情報を返すAPIを作成しました。
テストはすべてパスしてます。
=> add: getUsersInChannel API

backend/controllers/channel_test.go, backend/controllers/direct_message_test.go, backend/controllers/message_test.go, backend/controllers/setup.go, backend/controllers/test_func.go, backend/controllers/thread_test.go, backend/controllers/user_test.go, backend/controllers/workspace_test.go, backend/main.go, docker-compose.yml
フォルダ構成は変えないことにしました。色々考えましたが、共通で使うライブラリーをうまく配置できませんでした。
運用方法としては、setup.goのSetupRouter2関数に従来どおりAPIを追加します。server2で使う関数は従来のcontrollersやmodelsフォルダに作成します。
=> ２つ目のサーバー動作確認と、フォルダ構成の確定

README.md, backend/controllers/channel_test.go, backend/controllers/direct_message_test.go, backend/controllers/message_test.go, backend/controllers/test_func.go, backend/main.go, backend/models/base.go, backend/models/channels.go, backend/models/channels_and_users.go, backend/models/dm_lines.go, backend/models/mention.go, backend/models/messages.go, backend/models/messages_and_users.go, backend/models/thread_and_messages.go, backend/models/threads.go, backend/models/threads_and_user.go, backend/models/user.go, backend/models/workspace.go, backend/models/workspace_and_users.go, backend/testdata/run_api.go, backend/testdata/set_data.go, backend/testdata/testdata_main.go
使い方についてはreadmeに記載したので、そちらを参照してください。
テストツールをとりあえず、導入します。使っているうちに使いにくい改善してほしいところ出てきた改善するので、言ってください！
=> テストデータを作成ツールを作成

backend/controllerUtils/permissions.go, backend/controllers/message.go, backend/controllers/message_test.go
https://w1677379737-civ649113.slack.com/archives/C04RBNBFP34/p1689159031843669
この件に対応
=> public channelならチャンネルに参加していなくてもメッセージ一覧を取得できるように変更

backend/testdata/run_api.go, backend/testdata/set_data.go, backend/testdata/testdata_main.go
=> dmの情報もテストデータに追加

backend/controllerUtils/get_from_tables.go
バブルソートを利用していた箇所をgoのsort.sliceメソッドを利用したものに変更した。
=> ソートアルゴリズムを変更

backend/go.mod
使っていないモジュールを削除しました。
imagesを削除してからdocker-compose upしてバックエンドのテストをパスしているので、問題ないはずです。
=> いらないmoduleを削除
